### PR TITLE
Merge missing patches

### PR DESCRIPTION
**Pull request by PatrickRudolph**

### CODE REVIEW

**Comment by walterchris** [comment]
There is a patch tagged with NOTFORMERGE

**Comment by PatrickRudolph** [comment]
done

**Comment by walterchris** [comment]
We might want to test if this runs on real hardware like this. Otherwise LGTM

**Comment by PatrickRudolph** [comment]
Build tested on run on Hermes. No errors.

**Review by walterchris — APPROVED** [review]

**Pull request merged**
