### PR TITLE
UefiPayloadPkg: Scan for PCI devices after end of DXE

### PR DESCRIPTION
**Pull request by sylv-io**
This allows EFI applications to iterate over those devices.
An example is iPXE.efi that requires those devices to be present.

### CODE REVIEW

**Comment by sylv-io** [comment]
Guo:

```
Only trusted console devices would be connected in order to support TCG physical presence before ReadyToLock.  Instead of connect all PCI devices in PlatformBootManagerBeforeConsole (), please check why PlatformBootManagerAfterConsole() could not meet the requirement since all other PCI devices are expected to be connected using EfiBootManagerConnectAll ().
```

**Comment by sylv-io** [comment]
Guo:

Only trusted console devices would be connected in order to support TCG physical presence before ReadyToLock.  Instead of connect all PCI devices in PlatformBootManagerBeforeConsole (), please check why PlatformBootManagerAfterConsole() could not meet the requirement since all other PCI devices are expected to be connected using EfiBootManagerConnectAll ().

**Comment by sylv-io** [comment]
I have applied the change Guo suggested. This change has to be tested on real hardware with multiple PCI devices (e.g., two GPUs). Using qemu-x86_64 did not work in my case.

**Comment by Th3Fanbus** [comment]
Do we still need this?

**Pull request closed without merging**
