### PR TITLE
UefiPayloadPkg: Scan for Option ROMs

### PR DESCRIPTION
**Pull request by sylv-io**

### CODE REVIEW

**Comment by sylv-io** [comment]
Mail communication:

Ray:
```
Why running it will disable the ability of PciPlatform code to scan for ROMs?
I guess it is because the PciIoDevice->AllOpRomProcessed is set which causes GetPciRom() is skipped.
Can you explain more in the code comment?
```

Marcello:

```
> I guess it is because the PciIoDevice->AllOpRomProcessed is set which causes GetPciRom() is skipped.
exactly. Therefore we need this for the gPciPlatformProtocol implementation to work.
I will add this information as a code comment.

> In your UefiPayloadPkg change, you have an assumption that the option ROM BAR still contain the correct base address.
> Is it always true in real world? Do you think maybe the boot loader should supply a MMIO space range so UeifPayloadPkg
> can use for option rom decoding?
Every option ROM in coreboot does have it's own memory space and can not be provided as MMIO space range. Probably we could
add some kind of validation to verify the validity of the base address
```

Mike:
```
If the assumption in this env is that PCI enumeration has already been done, would it make
more sense for the component that performed PCI enumeration to collect the PCI Option ROM
contents and pass them into the UefiPayLoadPkg in memory buffers and have the PCI Platform Protocol
provide the PCI Option ROM images from these memory buffers?
```

**Comment by PatrickRudolph** [comment]
Response: We do not plan to add memory buffers to pass PCI Option ROMs.

**Comment by PatrickRudolph** [comment]
> Is it always true in real world? Do you think maybe the boot loader should supply a MMIO space range so UeifPayloadPkg
> can use for option rom decoding?

Response: 
We will update UefiPayloadPkg/BuildAndIntegrationInstructions.txt and make this a requirement for the boot loader to make all option ROM BARs contain a valid base address.

**Comment by Th3Fanbus** [comment]
Do we still need this?

**Pull request closed without merging**
